spring:
  application:
    name: mstsoftware
  output:
    ansi:
      enabled: always
  logging:
    level:
      org.flywaydb: DEBUG
  datasource:
    url: jdbc:mysql://localhost:3306/javaspringboot?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:database/migrations
    baseline-on-migrate: true

jwt:
  secret: a1M8O206XTw5ITl6NzReN3BKTTNVaWY1L1dnfWFPQjIjaysvV2F3Tm5fZA==
  expiration: 86400000
  issuer: https://mstsoftware.vn/
  refresh-token-ttl-days: 14